create database biblioteca;

use biblioteca;

CREATE TABLE Genero (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Genero VARCHAR(255) NOT NULL
) DEFAULT CHARSET utf8;

CREATE TABLE Livro (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Titulo VARCHAR(255) NOT NULL,
    Autor VARCHAR(255) NOT NULL,
    Genero INTEGER NOT NULL,
    FOREIGN KEY (Genero) REFERENCES Genero(ID),
    Prateleira INTEGER NOT NULL
) DEFAULT CHARSET utf8;

CREATE TABLE Cliente (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Telefone VARCHAR(20) NOT NULL,
    CPF VARCHAR(11) NOT NULL
) DEFAULT CHARSET utf8;

CREATE TABLE Emprestimo (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Livro INTEGER NOT NULL,
    FOREIGN KEY (Livro) REFERENCES Livro(ID),
    Cliente INTEGER NOT NULL,
    FOREIGN KEY (Cliente) REFERENCES Cliente(ID),
    Data_do_emprestimo DATETIME NOT NULL,
    Data_final DATETIME NOT NULL
) DEFAULT CHARSET utf8;

CREATE TABLE Devolucao (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Emprestimo INTEGER NOT NULL,
    FOREIGN KEY (Emprestimo) REFERENCES Emprestimo(ID),
    Data_de_devolucao DATETIME NOT NULL
) DEFAULT CHARSET utf8;